spring:
  application:
    name: webflux-playground
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
  sql:
    init:
      data-locations:
        - classpath:sql/data.sql

logging:
  level:
    org.springframework.r2dbc: TRACE

sec: sec09